### PR TITLE
Piece Repair

### LINKED ISSUE #39: Piece repair
When a miner gets deregistered, or happens to fail to respond with data it is supposed to store, that data should be requested from other miners, and redistributed across the network.

### PR DESCRIPTION
**Pull request by Shr1ftyy**
resolves #39 

periodic piece repair task in validator 

- modularized download code - separated logic into different helpers
- added table for miner to pieces mapping, and piece repair table
- added several helpers for querying the new tables and more
- added wip background piece repair task
- updated db schema
- update miner_pieces on piece repair tasks

### CODE REVIEW

File: crates/storb_validator/src/lib.rs [hunk 1]
```diff
@@ -228,6 +244,20 @@ pub async fn run_validator(config: ValidatorConfig) -> Result<()> {
...
+    // Spawn background piece repair task
+    tokio::spawn(async move {
+        let mut interval: time::Interval =
+            interval(Duration::from_secs(constants::PIECE_REPAIR_FREQUENCY));
+        loop {
+            interval.tick().await;
+            info!("Running piece repair task");
+            match repair::repair_pieces(validator_for_repair.clone()).await {
+                Ok(_) => debug!("Piece repair task completed successfully"),
+                Err(err) => error!("Piece repair task failed: {}", err),
```
Comment (rishiad) [inline crates/storb_validator/src/lib.rs:256]: either make both of them debug or both to be info, also how noisy is this error?

File: crates/storb_validator/src/repair.rs [hunk 2]
```diff
@@ -0,0 +1,279 @@
...
+                .clone()
+                .neuron
+                .read()
+                .await
+                .address_book
+                .get(&miner_uid)
+            {
+                Some(node_info) => node_info.clone(),
+                None => {
+                    error!("Miner UID {} not found in address book.", miner_uid);
```
Comment (rishiad) [inline crates/storb_validator/src/repair.rs:94]: maybe make this a debug or warn

File: crates/storb_validator/src/repair.rs [hunk 3]
```diff
@@ -0,0 +1,279 @@
...
+        // each miner_uid coresponds to the miner connection in miner_connections
+        let uid_to_connection: HashMap<NodeUID, Connection> = miner_uids
+            .iter()
+            .zip(miner_connections.iter())
+            .map(|(&uid, conn)| (uid, conn.1.clone()))
+            .collect();
+
+        upload::log_connection_success(&miner_connections);
+
+        // Distribute to miners, if there ar not enough miners, then we automatically loop back around the sorted_miners
```
Comment (rishiad) [inline crates/storb_validator/src/repair.rs:232]: *are

File: crates/storb_validator/src/repair.rs [hunk 4]
```diff
@@ -0,0 +1,279 @@
...
+                .clone()
+                .neuron
+                .read()
+                .await
+                .address_book
+                .get(&(miner_uid as u16))
+            {
+                Some(node_info) => node_info.clone(),
+                None => {
+                    error!("Miner UID {} not found in address book.", miner_uid);
```
Comment (rishiad) [inline crates/storb_validator/src/repair.rs:246]: make this a warn

File: crates/storb_validator/src/validator.rs [hunk 5]
```diff
@@ -458,7 +457,14 @@ impl Validator {
                         ) {
                             error!("Failed to update retrieval successes: {}", e);
                         }
+
                         let mut scoring_system_guard = self.scoring_system.write().await;
+
+                        // // Increase the missed pieces count
+                        // scoring_system_guard.increment_missed_pieces(challenge_result.piece_hash, challenge_result.miner_uid).unwrap_or_else(|e| {
+                        //     error!("Failed to increment missed pieces: {}", e);
+                        // });
```
Comment (rayokamoto) [inline crates/storb_validator/src/validator.rs:466]: is this still needed or can we remove this

File: migrations/scoresdb/20250222003351_db.up.sql
Comment (rayokamoto) [inline migrations/scoresdb/20250222003351_db.up.sql:1]: has the corresponding down migration been updated?

File: migrations/metadatadb/20250516054233_metadata_db.up.sql
Comment (rayokamoto) [inline migrations/metadatadb/20250516054233_metadata_db.up.sql:1]: has the corresponding down migration been updated?

**Review by rayokamoto — CHANGES_REQUESTED** [review]

File: crates/storb_validator/src/validator.rs (hunk 5 above)
Comment (Shr1ftyy) [reply crates/storb_validator/src/validator.rs:466]: I will remove it

**Review by rayokamoto — APPROVED** [review]
