### PR TITLE
DHT and API node rate limiting and more

### LINKED ISSUE #73: Validator downloads slow down to a crawl (or stop completely) due to blocking after some time
When a download takes a noticeable amount of time to complete (i.e. for larger files), the download process eventually slows to a crawl, or even seemingly just stop completely because it gets blocked. 

See the image below. The yellow areas highlight logs from what I think are part of the upload routine shortly before/after being blocked by something else:

Image

This requires further investigation.

### LINKED ISSUE #97: Peers getting booted from routing table - causes uploads to break
Uploads are a hit or miss, because peers occasionally get booted from the dht.

Successful upload example:
```
2025-04-20T11:12:33.252349Z DEBUG base::swarm::dht: 658: Received Put command
2025-04-20T11:12:33.252406Z DEBUG base::swarm::dht: 1186: Waiting for bootstrap to complete...
2025-04-20T11:12:33.252427Z DEBUG base::swarm::dht: 1194: Bootstrap completed.
2025-04-20T11:12:33.252442Z DEBUG base::swarm::dht: 1199: Checking DHT health...
2025-04-20T11:12:33.252496Z DEBUG base::swarm::dht: 1206: Connected peers: 2, Routing table entries: 1
2025-04-20T11:12:33.264909Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:12:33.267408Z DEBUG base::swarm::dht: 455: Put record succeeded with key: Key(b">\xe7\xed\xf6\0I\xce\xa6nq\"\x8bL\xb8\nFP\x9b\x1al\xc7\x0e\xdeQ\x11\xf1hgqL\xbe\xa7")
 and query id: QueryId(235)
2025-04-20T11:12:33.267701Z DEBUG storb_validator::upload: 594: Distributed pieces for chunk with hash Key(b">\xe7\xed\xf6\0I\xce\xa6nq\"\x8bL\xb8\nFP\x9b\x1al\xc7\x0e\xdeQ\x11\xf
1hgqL\xbe\xa7")
2025-04-20T11:12:33.267975Z DEBUG storb_validator::upload: 236: Raw Chunk hashes: [[41, 115, 1, 12, 20, 14, 73, 252, 26, 250, 22, 222, 53, 202, 55, 28, 146, 130, 121, 114, 87, 200
, 62, 181, 141, 178, 144, 6, 161, 234, 44, 234], [54, 91, 183, 82, 224, 2, 226, 183, 158, 148, 0, 113, 255, 220, 167, 160, 137, 130, 187, 125, 26, 61, 119, 100, 51, 187, 18, 199,
124, 47, 175, 124], [62, 231, 237, 246, 0, 73, 206, 166, 110, 113, 34, 139, 76, 184, 10, 70, 80, 155, 26, 108, 199, 14, 222, 81, 17, 241, 104, 103, 113, 76, 190, 167]]
2025-04-20T11:12:33.268076Z DEBUG storb_validator::upload: 238: Chunk hashes: ["2973010c140e49fc1afa16de35ca371c9282797257c83eb58db29006a1ea2cea", "365bb752e002e2b79e940071ffdca7a
08982bb7d1a3d776433bb12c77c2faf7c", "3ee7edf60049cea66e71228b4cb80a46509b1a6cc70ede5111f16867714cbea7"]
2025-04-20T11:12:33.269285Z DEBUG base::swarm::dht: 658: Received Put command
2025-04-20T11:12:33.269370Z DEBUG base::swarm::dht: 1186: Waiting for bootstrap to complete...
2025-04-20T11:12:33.269395Z DEBUG base::swarm::dht: 1194: Bootstrap completed.
2025-04-20T11:12:33.269412Z DEBUG base::swarm::dht: 1199: Checking DHT health...
2025-04-20T11:12:33.269459Z DEBUG base::swarm::dht: 1206: Connected peers: 2, Routing table entries: 1
2025-04-20T11:12:33.282792Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:12:33.284624Z DEBUG base::swarm::dht: 455: Put record succeeded with key: Key(b"7b40cfd3631d5fc5c9c1d307bbf2a2b878a11169cf6b59078c6b818f2a72c258") and query id: Quer
yId(236)
2025-04-20T11:12:33.284978Z DEBUG storb_validator::upload: 288: Inserted tracker entry with infohash 7b40cfd3631d5fc5c9c1d307bbf2a2b878a11169cf6b59078c6b818f2a72c258
2025-04-20T11:12:33.700076Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:12:33.720714Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:12:33.744428Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:12:33.762984Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:12:33.785089Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:12:33.801827Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:12:33.823895Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:12:33.843284Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
```

Failed upload example:

```
2025-04-20T11:14:16.716615Z DEBUG base::swarm::dht: 658: Received Put command
2025-04-20T11:14:16.716672Z DEBUG base::swarm::dht: 1186: Waiting for bootstrap to complete...
2025-04-20T11:14:16.716691Z DEBUG base::swarm::dht: 1194: Bootstrap completed.
2025-04-20T11:14:16.716708Z DEBUG base::swarm::dht: 1199: Checking DHT health...
2025-04-20T11:14:16.716749Z DEBUG base::swarm::dht: 1206: Connected peers: 1, Routing table entries: 0
2025-04-20T11:14:16.716774Z  WARN base::swarm::dht: 808: DHT health check failed, retrying...
2025-04-20T11:14:16.716789Z DEBUG base::swarm::dht: 1199: Checking DHT health...
2025-04-20T11:14:16.716819Z DEBUG base::swarm::dht: 1206: Connected peers: 1, Routing table entries: 0
2025-04-20T11:14:16.716840Z DEBUG base::swarm::dht: 1216: DHT appears unhealthy, forcing bootstrap
2025-04-20T11:14:16.717227Z ERROR base::swarm::dht: 1218: Failed to bootstrap: NoKnownPeers
2025-04-20T11:14:16.717294Z ERROR base::swarm::dht: 662: Error handling PutPiece command: "Failed to bootstrap DHT"

thread 'tokio-runtime-worker' panicked at crates/storb_validator/src/upload.rs:531:26:
Failed to put piece entry in DHT: RecvError(())
2025-04-20T11:14:16.717933Z ERROR storb_validator::routes: 174: The processor failed to process the upload: task 4420 panicked with message "Failed to put piece entry in DHT: Recv
Error(())"
2025-04-20T11:14:16.728898Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:14:16.750182Z DEBUG base::swarm::db: 303: Atomic batch write successful (1 ops)
2025-04-20T11:14:17.334088Z DEBUG Swarm::poll:drive{id=0}: quinn_proto::connection::packet_crypto: 28: discarding unexpected Handshake packet (567 bytes)
2025-04-20T11:14:17.334284Z DEBUG Swarm::poll:drive{id=0}: quinn_proto::connection::packet_crypto: 28: discarding unexpected Handshake packet (567 bytes)
2025-04-20T11:14:17.351042Z DEBUG Swarm::poll: libp2p_kad::handler: 448: New inbound connection peer=12D3KooWR9hiwUuuLkULNh894rTHBDw6LtF5cBDjc55h9J5shE9E mode=server
```

### PR DESCRIPTION
**Pull request by Shr1ftyy**
- switched to using dashmap for address book
- added rate limiting for `/info` endpoint and moved `local_node_info` directly into `ValidatorState` as a constant to help reduce blocking.
- added rate limiter for dht swarm requests
- made node info gathering concurrent by using futures
- increased min bandwidth requirement
- increase download channel buf size to resolve hangs during downloads.

resolves #97, resolves #73

### CODE REVIEW

File: crates/storb_base/src/constants.rs [hunk 1]
```diff
@@ -24,4 +24,17 @@ pub const DB_MPSC_BUFFER_SIZE: usize = 100;
 pub const CLIENT_TIMEOUT: Duration = Duration::from_secs(1);
 
 /// Timeout params for upload requests
-pub const MIN_BANDWIDTH: u64 = 10 * 1024; // minimum ~10KiB/s "bandwidth"
+pub const MIN_BANDWIDTH: u64 = 20 * 1024; // minimum ~100KiB/s "bandwidth"
+
+pub const DHT_MAX_RETRIES: u64 = 3; // maximum number of retries for DHT queries
```
Comment (Shr1ftyy) [inline crates/storb_base/src/constants.rs:29]: this is not being used - will need to remove.

File: crates/storb_validator/src/middleware.rs [hunk 2]
```diff
@@ -79,3 +89,35 @@ pub async fn require_api_key(
...
+    }
+
+    if timestamps.len() >= INFO_API_RATE_LIMIT_MAX_REQUESTS {
+        warn!("Rate limit exceeded for IP: {}", ip);
+        Err(StatusCode::TOO_MANY_REQUESTS)
+    } else {
+        timestamps.push_back(now);
+        drop(entry);
+        Ok(next.run(request).await)
+    }
```
Comment (rayokamoto) [inline crates/storb_validator/src/middleware.rs:122]: Why is `entry` only dropped in the else statement and not the if branch as well?

File: crates/storb_validator/src/middleware.rs [hunk 3]
```diff
@@ -79,3 +89,35 @@ pub async fn require_api_key(
...
+
+    let mut entry = limiter.entry(ip).or_default();
+    let timestamps: &mut VecDeque<Instant> = entry.value_mut();
+
+    while let Some(ts) = timestamps.front() {
+        if *ts < limit_start_time {
+            timestamps.pop_front();
+        } else {
+            break;
+        }
```
Comment (rayokamoto) [inline crates/storb_validator/src/middleware.rs:112]:
```suggestion
        if *ts >= limit_start_time {
            break;   
        }
        timestamps.pop_front();
```

File: crates/storb_validator/src/lib.rs [hunk 4]
```diff
@@ -155,11 +201,17 @@ pub async fn run_validator(config: ValidatorConfig) -> Result<()> {
     // Create main router with all routes
     let app = Router::new()
         .merge(protected_routes) // Add protected routes
-        .route("/info", get(node_info)) // Public route
+        .route(
+            "/info",
+            get(node_info).route_layer(from_fn(middleware::info_api_rate_limit_middleware)),
+        )
+        // Public route
```
Comment (rayokamoto) [inline crates/storb_validator/src/lib.rs:208]: Nitpick: this comment is rather out of place now, put it above `.route("/info", ...` at the very least

File: crates/storb_base/src/sync.rs [hunk 5]
```diff
@@ -132,68 +142,81 @@ impl Synchronizable for BaseNeuron {
...
+            }
+
+            if neuron_port == 0 {
+                error!("Invalid port for neuron: {:?}", neuron_info.uid);
+                continue;
+            }
+
+            let ip = Ipv4Addr::from((neuron_ip & 0xffff_ffff) as u32);
+            let url_raw = format!("http://{}:{}/info", ip, neuron_port);
+            let url = reqwest::Url::parse(&url_raw).expect("Invalid URL");
```
Comment (rayokamoto) [inline crates/storb_base/src/sync.rs:175]: Panicking probably isn't ideal, convert to error instead

File: crates/storb_base/src/sync.rs [hunk 6]
```diff
@@ -132,68 +142,81 @@ impl Synchronizable for BaseNeuron {
...
+                }
+            };
+
+            futures.push(future);
+        }
+
+        // Execute all futures concurrently and collect results
+        // TODO: make the buffer size constant - NO MAGIC NUMBERS!!!!1!!1!!
+        let stream = stream::iter(futures)
+            .buffer_unordered(32) // Limit to 32 concurrent requests
```
Comment (rayokamoto) [inline crates/storb_base/src/sync.rs:197]: Use constants?

File: crates/storb_base/src/swarm/dht.rs [hunk 7]
```diff
@@ -348,6 +335,38 @@ impl StorbDHT {
...
+        let key = (*peer_id, IpAddr::V4(*ip_addr));
+        let mut entry = self.swarm_rate_limits.entry(key).or_default();
+        let timestamps = entry.value_mut();
+
+        while let Some(ts) = timestamps.front() {
+            if *ts < limit_start_time {
+                timestamps.pop_front();
+            } else {
+                break;
+            }
```
Comment (rayokamoto) [inline crates/storb_base/src/swarm/dht.rs:358]:
```suggestion
            if *ts >= limit_start_time {
                break;
            }
            timestamps.pop_front();
```

**Review by rayokamoto — CHANGES_REQUESTED** [review]

**Review by rayokamoto — APPROVED** [review]
